import {Bricolage_Grotesque} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ThemeProvider";
import NextTopLoader from 'nextjs-toploader'; 

const bricolage_grotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "DayaTube",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={bricolage_grotesque.className}
      >
        <ThemeProvider attribute="class"
          defaultTheme="light"
          
          disableTransitionOnChange >
            
        {children}
        </ThemeProvider>
        
      </body>
    </html>
  );
}
